from enum import Enum, auto

HEARTBEAT_TIME = 5
LISTENING = 10
MAX_TRANSMISSION_DELAY = 5
MAX_PROCESSING_DELAY = 2
TOTAL_DELAY = (2 * MAX_TRANSMISSION_DELAY) + MAX_PROCESSING_DELAY
BUFF_SIZE = 1024
DEFAULT_ID = -1

REGISTER = 4
SOCKET_TIMEOUT = 10
MAX = 1000
MIN = 1


class Type(Enum):
    ELECTION = 0
    END = 1
    ANSWER = 2
    HEARTBEAT = 3
    REGISTER = 4
    ACK = 5
    SUBSCRIBE = 6
    PING = 7
    CONNECT_TO_CLIENT = 8
    PUBLISH_DATA_TO_SUBSCRIBERS = 9
    UPDATE_BUSINESS_TYPE = 10
    PUBLISH_OFFER = auto()
    UPDATE_INTERESTS = auto()

# New default configurations
DEFAULT_BUSINESS_TYPE = "General"
MAX_MESSAGE_SIZE = 4096

# New error codes
class ErrorCode(Enum):
    UNREGISTERED_NODE = 1
    INVALID_BUSINESS_TYPE = 2
    MESSAGE_SIZE_EXCEEDED = 3
